id = "chuckcoughlin.charlie"
version = "1.0.0"
name = { en = "Irish", zh = "Irish" }
logo = "/res/shamrock.png"
description = "Python Agent for Irish Dancing"
entry = "src/Irish.py:IrishAgent"
debuggable = true

[requirements]
min_api_level = 10700
models = [ "Booster T1", "Booster K1" ]